version: '3.8'
services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5000:5432" # Host port 5000 is mapped to container port 5432
    volumes:

      - C:/Users/Dell/db_volumes/patient-service-db:/var/lib/postgresql