version: '3.8'
services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5000:5432" # Host port 5000 is mapped to container port 5432
    volumes:

      - C:/Users/Dell/db_volumes/patient-service-db:/var/lib/postgresql


    # kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway" # Helps Linux/some Windows setups resolve the host
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      # MAGIC LINE: Connects to the Kafka running in IntelliJ
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS:  192.168.31.168:9094