server:
  port: 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. Auth Service Route
        - id: auth-service-route
          uri: http://auth-service:4005   # Docker internal name
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # 2. Patient Service Route
        - id: patient-service-route
          uri: http://patient-service:4000 # Docker internal name
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            # - JwtValidation  # Calls your Java Factory

        # 3. API Docs (Patient)
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs

        # 4. API Docs (Auth)
        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth, /v3/api-docs

# --- Required for your Java Filter ---
auth:
  service:
    url: http://auth-service:4005

# --- UNLOCK THE ROUTES PAGE (New Section) ---
management:
  endpoints:
    web:
      exposure:
        include: gateway